### PR TITLE
Added support for a second modbus meter

### PR DESCRIPTION
**Pull request by magpern**
Added support for a second modbus meter. Solaredge supports up to three meters.
This was pretty much a copy paste job, and it could probably be made more pretty by extracting the data collection in a shared function and calling it with parameters. The only difference between meters is the modbus start address.
But, my python knowledge is limited, and this PR solves the problem with two meters.

image

### CODE REVIEW

**Comment by daballiemo** [comment]
When can we expect a merge, my external meter is meter 2 ;-)

**Comment by erikarenhill** [comment]
sorry for late reply on this, I will have a look and maybe we can just reuse the `SolarEdgeMeterSensor2` class and passing start-register/name as parameters to the constructor instead

**Comment by erikarenhill** [comment]
@magpern @daballiemo I opened up a new pull request https://github.com/erikarenhill/solaredge-modbus-hass/pull/22 where we instead reuse the same class and pass a unit id, can someone of you please test this as I dont have any external meter. I'll merge it when someone has verified, thanks!

**Comment by mkrasselt1** [comment]
Since this may need more work and I am not good engough for Python:
Found this repo, installable via hacs, supports the new homeassitant energy management and reads hundreds of values and detects a lot as i need:
https://github.com/Tapematch/home-assistant-solaredge-modbus

**Pull request closed without merging**
